version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/go-test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
