M48
; DRILL file {KiCad (6.0.0-0)} date Monday, January 03, 2022 at 01:42:33 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-03T13:42:33-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X203.5Y-97.5
X203.5Y-120.5
X261.5Y-97.5
X261.5Y-120.5
T0
M30
