class ReturnCodes:
    DELETEFILE_SUCCESS = 0
    DELETEFILE_FILE_NOT_FOUND = 1
    RENAMEFILE_SUCCESS = 10
    RENAMEFILE_UNABLE_TO_MOVE = 11
    DOWNLOADFILETOISO_SUCCESS = 20
    DOWNLOADTODIR_SUCCESS = 30


