.TH rascsi 1
.SH NAME
rasctl \- Sends management commands to the rascsi process
.SH SYNOPSIS
.B rasctl
\fB\-l\fR |
\fB\-s\fR |
[\fB\-g\fR \fILOG_LEVEL\fR]
[\fB\-h\fR \fIHOST\fR]
[\fB\-p\fR \fIPORT\fR]
[\fB\-v\fR]
\fB\-i\fR \fIID\fR
[\fB\-c\fR \fICMD\fR]
[\fB\-f\fR \fIFILE\fR]
[\fB\-n\fR \fINAME\fR]
[\fB\-t\fR \fITYPE\fR]
[\fB\-u\fR \fIUNIT\fR]
.SH DESCRIPTION
.B rasctl
Sends commands to the rascsi process to make configuration adjustments at runtime or to check the status of the devices.

Either the -i or -l option should be specified at one time. Not both. 

You do NOT need root privileges to use rasctl.

Note: The command and type arguments are case insensitive. Only the first letter of the command/type is evaluated by the tool.

.SH OPTIONS
.TP
.BR \-g\fI " "\fILOG_LEVEL
The rascsi log level to set (trace, debug, info, warn, err, critical, off)
.TP
.BR \-h\fI " " \fIHOST
The rascsi host to connect to, default is 'localhost'.
.TP
.BR \-l\fI
List all of the devices that are currently being emulated by RaSCSI, as well as their current status.
.TP
.BR \-p\fI " " \fIPORT
The rascsi port to connect to, default is 6868.
.TP
.BR \-s\fI
Display the server-side configuration settings.
.TP
.BR \-v\fI " " \fI
Display the rascsi version.
.TP
.BR \-i\fI " " \fIID
ID is the SCSI ID that you want to control. (0-7)
.TP 
.BR \-c\fI " " \fICMD
Command is the operation being requested. options are:
   attach: attach disk
   detach: detach disk
   insert: insert media (removable media devices only)
   eject: eject media (removable media devices only)
   protect: write protect the media (not for CD-ROMs, which are always read-only)
   unprotect: remove write protection from the media (not for CD-ROMs, which are always read-only)
.IP
eject, protect and unprotect are idempotent.
.TP 
.BR \-f\fI " " \fIFILE
Path to the disk image file. See the rascsi(1) man page for allowable file types.
.TP 
.BR \-t\fI " " \fITYPE
Specifies the device type. This type overrides the type derived from the file extension of the specified image. See the rascsi(1) man page for the available device types. Legacy drive types are:
   hd: Hard disk (SCSI or SASI)
   mo: Magneto-Optical disk
   cd: CD-ROM
   bridge: Bridge device (This is only applicable to the Sharp X68000)
.TP 
.BR \-u\fI " " \fIVENDOR:PRODUCT:REVISION
The vendor, product and revision for the device, to be returned with the INQUIRY data. A complete set of name components must be provided. VENDOR may have up to 8, PRODUCT up to 16, REVISION up to 4 characters. Padding with blanks to the maxium length is automatically applied. Once set the name of a device cannot be changed.
.TP 
.BR \-u\fI " " \fIUNIT
Unit number (0 or 1). This will default to 0. This option is only used when there are multiple SCSI devices on a shared SCSI controller. (This is not common)

.SH EXAMPLES
Show a listing of all of the SCSI devices and their current status.
   rasctl -l


Example output:
   +----+----+------+-------------------------------------
   | ID | UN | TYPE | DEVICE STATUS
   +----+----+------+-------------------------------------
   |  0 |  1 | SCHD | /home/pi/harddisk.hda
   +----+----+------+-------------------------------------

Request the RaSCSI process to attach a disk (assumed) to SCSI ID 0 with the contents of the file system image "HDIIMAGE0.HDS".
   rasctl -i 0 -f HDIIMAGE0.HDS

.SH SEE ALSO
rascsi(1) scsimon(1)

Full documentation is available at: <https://www.github.com/akuker/RASCSI/wiki/>
