.Dd December 18, 2025
.Dt SCSICTL 1
.Os PiSCSI
.Sh NAME
.Nm scsictl
.Nd Sends management commands to the piscsi process
.Sh SYNOPSIS
.Nm
.Op Fl b Ar BLOCK_SIZE
.Op Fl C Ar FILENAME:FILESIZE
.Op Fl c Ar CMD
.Op Fl d Ar FILENAME
.Op Fl E Ar FILENAME
.Op Fl F Ar IMAGE_FOLDER
.Op Fl f Ar FILE|PARAM
.Op Fl h Ar HOST
.Op Fl i Ar ID Ns Oo : Ar LUN Oc
.Op Fl L Ar LOG_LEVEL
.Op Fl n Ar NAME
.Op Fl P
.Op Fl p Ar PORT
.Op Fl R Ar CURRENT_NAME:NEW_NAME
.Op Fl r Ar RESERVED_IDS
.Op Fl s Oo Ar FOLDER_PATTERN:FILE_PATTERN:OPERATIONS Oc
.Op Fl t Ar TYPE
.Op Fl u Ar UNIT
.Op Fl x Ar CURRENT_NAME:NEW_NAME
.Op Fl z Ar LOCALE
.Nm
.Op Fl D | e | I | l | m | N | O | o | S | T | V | v | X
.Sh DESCRIPTION
.Nm
sends commands to the piscsi process to make configuration adjustments at runtime or to check the status of the devices.
.Pp
Either the -i or -l option should be specified at one time. Not both.
.Pp
You do NOT need root privileges to use scsictl. scsictl also runs on non-Pi Linux platforms.
.Pp
Note: The command and type arguments are case insensitive. Only the first letter of the command/type is evaluated by the tool.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b Ar BLOCK_SIZE
The optional block size, either 512, 1024, 2048 or 4096 bytes. The default size is 512 bytes.
.It Fl C Ar FILENAME:FILESIZE
Create an image file in the default image folder with the specified name and size in bytes.
.It Fl c Ar CMD
Command is the operation being requested. Options are:
.Bl -bullet -compact
.It
a(ttach): Attach disk
.It
d(etach): Detach disk
.It
i(nsert): Insert media (removable media devices only)
.It
e(ject): Eject media (removable media devices only)
.It
p(rotect): Write protect the medium (not for CD-ROMs, which are always read-only)
.It
u(nprotect): Remove write protection from the medium (not for CD-ROMs, which are always read-only)
.It
s(how): Display device information
.El
.Pp
eject, protect and unprotect are idempotent.
.It Fl D
Detach all devices.
.It Fl d Ar FILENAME
Delete an image file in the default image folder.
.It Fl E Ar FILENAME
Display information on an image file.
.It Fl e
List all images files in the default image folder.
.It Fl F Ar IMAGE_FOLDER
Set the default image folder.
.It Fl f Ar FILE|PARAM
Device-specific: Either a path to a disk image file, or a parameter for a non-disk device. See the piscsi(1) man page for permitted file types.
.It Fl I
Gets the list of reserved device IDs.
.It Fl i Ar ID Ns Oo : Ar LUN Oc
The SCSI ID and optional LUN that you want to control. (0-7:0-31)
.It Fl L Ar LOG_LEVEL
Set the piscsi log level (trace, debug, info, warning, error, off).
.It Fl l
List all of the devices that are currently being emulated by PiSCSI, as well as their current status.
.It Fl h Ar HOST
The piscsi host to connect to, default is 'localhost'.
.It Fl m
List all file extensions recognized by PiSCSI and the device types they map to.
.It Fl N
Lists all available network interfaces provided that they are up.
.It Fl n Ar VENDOR:PRODUCT:REVISION
The vendor, product and revision for the device, to be returned with the INQUIRY data. A complete set of name components must be provided. VENDOR may have up to 8, PRODUCT up to 16, REVISION up to 4 characters. Padding with blanks to the maxium length is automatically applied. Once set the name of a device cannot be changed.
.It Fl O
Display the available piscsi server log levels and the current log level.
.It Fl o
Display operation meta data information.
.It Fl P
Prompt for the access token in case piscsi requires authentication.
.It Fl p Ar PORT
The piscsi port to connect to, default is 6868.
.It Fl R Ar CURRENT_NAME:NEW_NAME
Rename an image file in the default image folder.
.It Fl r Ar RESERVED_IDS
Comma-separated list of IDs to reserve. Pass an empty list in order to not reserve anything.
.It Fl S
Display statistics.
.It Fl s Oo Ar FOLDER_PATTERN:FILE_PATTERN:OPERATIONS Oc
Display server-side settings like available images or supported device types.
.It Fl T
Display all device types and their properties.
.It Fl t Ar TYPE
Specifies the device type. This type overrides the type derived from the file extension of the specified image. See the piscsi(1) man page for the available device type codes, or use a shorthand (only the first letter is required):
.Bl -bullet -compact
.It
cd: CD-ROM
.It
daynaport: DaynaPort Network Adapter
.It
hd: Hard Disk
.It
services: Host Services
.It
printer: Printer
.It
mo: Magneto-Optical Drive
.It
removable: Removable Hard Disk
.It
tape: Tape Drive
.El
.It Fl V
Display the scsictl version.
.It Fl v
Display the piscsi server version.
.It Fl X
Shut down the piscsi process.
.It Fl x Ar CURRENT_NAME:NEW_NAME
Copy an image file in the default image folder.
.It Fl z Ar LOCALE
Overrides the default locale for client-facing error messages.
.It Fl u Ar UNIT
Unit number (0-31). This will default to 0. This option is only used when there are multiple SCSI devices on a shared SCSI controller. (This is not common)
.El
.Sh EXAMPLES
Show a listing of all of the SCSI devices and their current status.
.Dl Nm scsictl Fl l
.Pp
Example output:
.Bd -literal -offset indent
+----+-----+------+-------------------------------------
| ID | LUN | TYPE | IMAGE FILE
+----+-----+------+-------------------------------------
|  0 |   1 | SCHD | /home/pi/harddisk.hda
+----+-----+------+-------------------------------------
.Ed
.Pp
Request the PiSCSI process to attach a disk (assumed) to SCSI ID 0 with the contents of the file system image "HDIIMAGE0.HDS".
.Dl Nm scsictl Fl i 0 Fl f HDIIMAGE0.HDS
.Sh SEE ALSO
.Xr piscsi 1 ,
.Xr scsimon 1 ,
.Xr scsidump 1
.Pp
Full documentation is available at: <https://www.piscsi.com>
