.Dd December 5, 2022
.Dt SCSILOOP 1
.Os
.Sh NAME
.Nm scsiloop
.Nd Tool for testing the PiSCSI board with a loopback adapter installed
.Sh SYNOPSIS
.Nm
.Op Fl L Ar LOG_LEVEL
.Sh DESCRIPTION
.Nm
Performs a self-test of the PiSCSI hardware to ensure that the board is functioning properly. In order for this tool to work, a special loopback cable MUST be attached to the PiSCSI SCSI connector.
.Pp
In addition to testing the GPIO signals, scsiloop will perform a self-test of the hardware timers that are built into the system on a chip (SoC).
.Pp
The loopback connections for the DB25 connector are shown here:
.Bd -literal -offset indent
|Pin | Name | Pin | Name |
+----+------+-----+------+
|  1 | REQ  | 13  | DB7  |
|  2 | MSG  | 12  | DB6  |
|  3 | I/O  | 11  | DB5  |
|  4 | RST  | 10  | DB3  |
|  5 | ACK  |  8  | DB0  |
|  6 | BSY  | 20  | DBP  |
| 15 | C/D  | 23  | DB4  |
| 17 | ATN  | 22  | DB2  |
| 19 | SEL  | 21  | DB1  |
.Ed    

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl L Ar LOG_LEVEL
The piscsi log level (trace, debug, info, warn, err, off). The default log level is 'info'.
.El

.Sh SEE ALSO
.Xr scsictl 1 ,
.Xr piscsi 1 ,
.Xr scsimon 1
.Pp
Full documentation is available at: <https://www.piscsi.com>
