.TH rascsi 1
.SH NAME
rasctl \- Sends management commands to the rascsi process
.SH SYNOPSIS
.B rasctl
\fB\-l\fR |
\fB\-i\fR \fIID\fR
[\fB\-u\fR \fIUNIT\fR]
[\fB\-c\fR \fICMD\fR]
[\fB\-t\fR \fITYPE\fR]
[\fB\-f\fR \fIFILE\fR]
.SH DESCRIPTION
.B rasctl
Sends commands to the rascsi process to make configuration adjustments at runtime or to check the status of the devices.

Either the -i or -l option should be specified at one time. Not both. 

You do NOT need root privileges to use rasctl.

Note: The command and type arguments are case insensitive. Only the first letter of the command/type are evaluated by the tool.

.SH OPTIONS
.TP
.BR\-\-l\fI
List all of the devices that are currently being emulated by RaSCSI, as well as their current status. \n
.TP
.BR\-\-i\fI " " \fIID
ID is the SCSI ID that you want to control. (0-7)\n
.TP 
.BR\-\-u\fI " " \fIUNIT
Unit number (0 or 1). This will default to 0. This option is only used when there are multiple SCSI devices on a shared SCSI controller. (This is not common)\n
.TP 
.BR\-\-c\fI " " \fICMD
Command is the operation being requested. options are:
   attach: attach disk
   detach: detach disk
   insert: insert media (Magneto-Optical and CD only)
   eject:  eject media  (Magneto-Optical and CD only)
   protect: Write protect the media (Magneto-Optical only)
.IP
When the command is omited, rasctl will default to the 'attach' command
.TP 
.BR\-\-t\fI " " \fITYPE
Specifies the type of disk. If this disagrees with the file extension of the specified image, the TYPE argument is ignored. Available drive types are:
   hd: Hard disk (SCSI or SASI)
   mo: Magneto-Optical disk)
   cd: CD-ROM
   bridge: Bridge device (This is only applicable to the Sharp X68000)
.TP 
.BR\-\-f\fI " " \fIFILE
Path to the disk image file. See the rascsi(1) man page for allowable file types.

.SH EXAMPLES
Show a listing of all of the SCSI devices and their current status
   rasctl -l


Example output:
   +----+----+------+-------------------------------------
   | ID | UN | TYPE | DEVICE STATUS
   +----+----+------+-------------------------------------
   |  0 |  1 | SCHD | /home/pi/harddisk.hda
   +----+----+------+-------------------------------------

Request the RaSCSI process to attach a disk (assumed) to SCSI ID 0 with the contents of the file system image "HDIIMAGE0.HDS".
   rasctl -i 0 -f HDIIMAGE0.HDS

.SH SEE ALSO
rascsi(1)

Full documentation is available at: <https://www.github.com/akuker/RASCSI/wiki/>
