"""
Module for return codes that are refrenced in the return payloads of the piscsi module.
"""


# pylint: disable=too-few-public-methods
class ReturnCodes:
    """Class for the return codes used within the piscsi module."""

    DELETEFILE_SUCCESS = 0
    DELETEFILE_FILE_NOT_FOUND = 1
    DELETEFILE_UNABLE_TO_DELETE = 2
    RENAMEFILE_SUCCESS = 10
    RENAMEFILE_UNABLE_TO_MOVE = 11
    DOWNLOADFILETOISO_SUCCESS = 20
    DOWNLOADTODIR_SUCCESS = 30
    WRITEFILE_SUCCESS = 40
    WRITEFILE_COULD_NOT_WRITE = 41
    WRITEFILE_COULD_NOT_OVERWRITE = 42
    READCONFIG_SUCCESS = 50
    READCONFIG_COULD_NOT_READ = 51
    READCONFIG_INVALID_CONFIG_FILE_FORMAT = 52
    READDRIVEPROPS_SUCCESS = 70
    READDRIVEPROPS_COULD_NOT_READ = 71
    ATTACHIMAGE_COULD_NOT_ATTACH = 80
    EXTRACTIMAGE_SUCCESS = 90
    EXTRACTIMAGE_NO_FILES_SPECIFIED = 91
    EXTRACTIMAGE_NO_FILES_EXTRACTED = 92
    EXTRACTIMAGE_COMMAND_ERROR = 93
    UNDER_VOLTAGE_DETECTED = 100
    ARM_FREQUENCY_CAPPED = 101
    CURRENTLY_THROTTLED = 102
    SOFT_TEMPERATURE_LIMIT_ACTIVE = 103
    UNDER_VOLTAGE_HAS_OCCURRED = 116
    ARM_FREQUENCY_CAPPING_HAS_OCCURRED = 117
    THROTTLING_HAS_OCCURRED = 118
    SOFT_TEMPERATURE_LIMIT_HAS_OCCURRED = 119
