#!/bin/sh
# Generate the Go project version from the authoritative C++ version constants.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source_file="$script_dir/../../cpp/shared/piscsi_version.cpp"
output_file="$script_dir/version_generated.go"

if [ "${1:-}" = "--check" ]; then
	check_only=1
	shift
else
	check_only=0
fi

if [ "$#" -ne 0 ]; then
	echo "Usage: $0 [--check]" >&2
	exit 2
fi

version=$(awk -F '[=;]' '
	/^const int piscsi_major_version =/ { major = $2 + 0; have_major = 1 }
	/^const int piscsi_minor_version =/ { minor = $2 + 0; have_minor = 1 }
	/^const int piscsi_patch_version =/ { patch = $2 + 0; have_patch = 1 }
	END {
		if (!have_major || !have_minor || !have_patch) {
			exit 1
		}
		if (patch < 0) {
			printf "%02d.%02d --DEVELOPMENT BUILD--", major, minor
		} else {
			printf "%02d.%02d.%02d", major, minor, patch
		}
	}' "$source_file") || {
	echo "Could not determine PiSCSI project version from $source_file" >&2
	exit 1
}

temporary_file=$(mktemp "${output_file}.XXXXXX")
trap 'rm -f "$temporary_file"' EXIT HUP INT TERM
printf '%s\n\n%s\n\n%s\n' \
	'// Code generated by generate_version.sh; DO NOT EDIT.' \
	'package piscsi' \
	"const ProjectVersion = \"$version\"" > "$temporary_file"

if [ "$check_only" -eq 1 ]; then
	if ! cmp -s "$temporary_file" "$output_file"; then
		echo "$output_file is stale; run $script_dir/generate_version.sh" >&2
		exit 1
	fi
	exit 0
fi

mv "$temporary_file" "$output_file"
trap - EXIT HUP INT TERM
